main/src/main/java/com/sedmelluq/discord/lavaplayer/source/bandcamp/BandcampAudioSourceManager.java

Fixed Bandcamp regexes so that
https://cysmix.bandcamp.com/album/escapism/
is just as valid as
https://cysmix.bandcamp.com/album/escapism
Regexes have only been tested on http://www.regexpal.com/, not at actual runtime

Fix Bandcamp regexes not matching links ending with `/`

---

README.md

AudioTrack doesn't have mayStartNext, AudioTrackEndReason does.

Fixed a method call in README

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/format/transcoder/PcmChunkDecoder.java

Hello.
When I try to change the volume of an audio player currently playing a track using `PCM_S16_LE` or `PCM_S16_BE` as the codec, the frame buffer is not rebuilt correctly. This does not happen when using Opus. Trying to get audio data using `AudioPlayer.provide().data` returns an empty byte array containing **0 elements** `({} not {0,0,0,.......})` until all rebuilt frames are read from the frame buffer. After some debugging I believe the problem is caused by [line 63](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/filter/volume/PcmVolumeProcessor.java#L63) and [line 76](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/filter/volume/PcmVolumeProcessor.java#L76) in …

Fix bug when changing volume using PCM

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchProvider.java

It seems YouTube [changed their DOM on the search results page](https://github.com/sedmelluq/lavaplayer/issues/45#issuecomment-319029147).
This leads to the AudioTrack being built not having the necessary elements. (like the track length)

Update the `durationElement` selector

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/beam/BeamAudioSourceManager.java

https://blog.mixer.com/welcome/

Add support for beam's new name: mixer.com

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java

Normally the HttpAudioSourceManager would redirect a non-desktop page for us.
If this sourcemanager has been disabled, then mobile links don't work anymore.
~~Tested this out, this seems to work as is, although I don't know what
streams are available for download on the mobile version of YouTube.~~
Forgot that it piggybacks off of the normal `getWatchUrl` based logic.

Fix mobile YouTube links

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/local/LocalAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/local/LocalAudioTrack.java

Implemented the #encodeTrack and #decodeTrack methods for the LocalAudioSourceManager. I don't know why these weren't originally implemented so if there's a reason feel free to close :)

Local audio source track encoding

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/bandcamp/BandcampAudioTrack.java

Lately we've found that no URLs load, since these URLs already contain the https:// protocol.

Fix fixup of protocol in bandcamp URLs

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java

I think since the new website for Twitch is live they use a new URL.
This PR adds that to the regex, so that it can match.

Allow the go.twitch.tv url to match

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/beam/BeamSegmentUrlProvider.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/stream/M3uStreamSegmentUrlProvider.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamSegmentUrlProvider.java

This solves the intermittent 403s.
Example change:
```
newUri = https://video-edge-c55f64.ams02.hls.ttvnw.net/v1/segment/CtcClbSUIeqGAkPEY52nwDCBslkcbCiH904ryM28uxlwFuAe1MlREy14si_Rl4-xf1KXFCTtVXZV-3kPcgdYVAq99mXjWq4zEZtP7Ozrj1g7ID1YZUhHk8xcmWgZKULJiV8Bq5pJfT86FivKChl-FI4h6nhEaGBPeEnJ8LfIqx-Lc2pJU3Yikm-lSCjR-WxeFqpC34-Tj3Fin5UE8D1FHZGkKycXIXc3hfVg-Fru0XWjG-oenFyA6ziDQcnWxZqeHA8fbNtn36i3yJH7RAb-EfD7LSmZrAQVCBxEyUqnnXhzpVQP2N1r46qu0ibxB6dHPnO0sOgs-zXZFwrtQaqFFQEyG0S4jhsD1Fkod0KAulpTCCLmSTeBDOtFPcBt_Flrgtk5Fe-LlyGUmvEHSLmBHdOYRXJouJ8tJM-tQ1hdMX1WNk_MZ8SglF_AQj_nC-Dc05TrpmVxNaxv4hIQF9kJ_u2NpFZyqiwBk7mvHRoMak8zlX76NR50E9i5.ts
oldUri = https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/https://video-edge-c55f64.ams02.hls.ttvnw.net/v1/segment/CtcCokCG8bSpOD6T_7PdiMrFTTPkOGSQCOY-1IGCSVUMObJkUt6t …
```

Correctly resolve the twitch stream segments

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java

This would allow links with `&feature=youtu.be` to match, and I noticed that the regex handling relies on the `list` parameter to be always there.

Improve loading of YouTube tracks

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/filter/ChannelCountPcmAudioFilter.java

I tried using the ChannelCounterPcmAudioFilter for some custom audio processing where I needed to convert from stereo to mono and I started getting ``BufferUnderflowException``s:
```
[13:22:39] [JDA AudioConnection Guild: 220674061808697344 Receiving Thread/ERROR]: There was some random exception while waiting for udp packets
java.nio.BufferUnderflowException: null
at java.nio.Buffer.nextGetIndex(Buffer.java:628) ~[?:?]
at java.nio.HeapShortBuffer.get(HeapShortBuffer.java:175) ~[?:?]
at com.sedmelluq.discord.lavaplayer.filter.ChannelCountPcmAudioFilter.processNormalizer(ChannelCountPcmAudioFilter.java:68) ~[heisenberg.jar:18.04.05.151422]
at com.sedmelluq.discord.lavaplayer.filter.ChannelCountPcmAudioFilter.process(ChannelCountPcmAudioFilter.java:41) ~[heisenberg.jar:18.04.05.151422]
at …
```

Fix BufferUnderflowException in ChannelCountPcmAudioFilter

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayer.java

Some older songs on YouTube (usually dated before 2009) are usually quieter in terms of volume. 150 sometimes isn't enough to compensate for the lacking volume. This PR removes the hard-coded limit in favor of allowing developers to set their own limits.

Remove hard-coded maximum volume limit

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java

This PR fixes reading Twitch streams by using the new Helix API and obtaining data from the response.
If the stream is offline, it will return null.

Fixed Twitch streams by using the Helix API

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java

I have tested these changes by overriding the YoutubeAudioSourceManager class in my project that uses lavaplayer.

Fix for playing YouTube videos from the embed page

---

common/build.gradle
common/src/main/java/com/sedmelluq/discord/lavaplayer/natives/Architecture.java
common/src/main/java/com/sedmelluq/discord/lavaplayer/natives/NativeLibLoader.java

As discussed on Discord with @sedmelluq, these changes make it easy to run Lavalink and other projects that embed lavaplayer on more exotic architectures like ARM without modifying the `udp-queue` and `lavaplayer-native` jars. Instead, the native libraries can be built separately for the platform of interest, then used directly by setting a system property.
This change has been tested to work with Lavalink on:
- x86_64: Windows, OSX and Linux
- ARM: Linux on armv7 and armv8 (aarch64)
Loading of ALL native libraries through `NativeLibLoader` can now be controlled by:
- `lavaplayer.native.arch` : overrides the detected OS architecture, e.g. `armhf`, `x86`
- `lavaplayer.native.dir` : look in `{dir}/{system}/` for libraries
- `lavaplayer.native.system` : overrides the detected system, e.g. …

More arch detection, read lib locations, etc. from properties

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/SoundCloudAudioSourceManager.java

Loading tracks via direct URL (e.g. <https://soundcloud.com/itsrudeboy/love-sorrow>) throw `com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.`

Fix SoundCloud direct URL playback

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioTrack.java

Fixes in this PR:
- Formats with no cipher, thus have no `cipher` property (NullPointerException)
- Videos that are unavailable/copyrighted/deleted but Lavaplayer wasn't aware due to not checking the status in `player_response` JSON (NullPointerException, and in some cases, `No formats`(?) error that was caused by videos that are not available in the region that Lavaplayer is being used in (geo-restricted).
- Checking `playabilityStatus` in `player_response` to determine whether a video is playable. (`IllegalStateException: Get only works on a map`)

Fix NPEs and playabilityStatus check

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java

Duplicate query parameters such as `t=10&t=20` would cause a track to not load (due to a duplicate key exception), this makes it use the first defined query parameter with that key

Fix duplicate query parameters

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioTrack.java

Prevents NPEs from happening when attempting to play certain YouTube tracks.
Example: https://www.youtube.com/watch?v=hDMtLbMSp0w
Not completely tested because Gradle is being a PITA. Also not very elegant either.

Don't fail when given YT format without contentLength

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioTrack.java

Adds a check for null details due to an unavailable video on YouTube's end.
This pull request fixes issue #258

Add null check for youtube track details (Closes #258)

---

README.md

JCenter will soon not support HTTP anymore: https://jfrog.com/blog/secure-jcenter-with-https/

Use HTTPS for JCenter url

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetailsLoader.java

Using the old way of getting the video infos from the EmbedPage again for age restricted songs.
Got it running in prod for a few weeks without issues.

feat: Ability to play age restricted songs again

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/SoundCloudAudioSourceManager.java

Tracks that are not available (https://soundcloud.com/ninjx/catch-these-hands for example) throw an NPE since DefaultSoundCloudDataReader#findTrackData returns null for them

Fix NPE for unavailable soundcloud tracks

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/DefaultSoundCloudPlaylistLoader.java

This fixes an issue where trying to resolve more than 50 track IDs at once would cause SoundCloud to return `400: Bad Request`.
This has been tested with some of the erroneous URLs listed in #284, and all of them are now working.

[SoundCloud] Partition track IDs by 50 elements

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetails.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeMpegStreamAudioTrack.java

- Removes contentLength check for livestreams. This should default to itag 140 (`audio/mp4`).
- Adds a basic retry mechanism to `YoutubeMpegStreamAudioTrack`. When it requests the next segment, if it receives a 204 or the content length is 0, it will wait 400ms before requesting again.
- This is basic in the sense that it will only retry once before giving up and marking the stream as finished.
A delay of 400ms *should* be fine. I tested this with 250ms delay originally and the stream lasted for 24 minutes before finishing. There is no jitter/audible choppiness with a 400ms delay.

Fix loading of YouTube livestreams, and add basic retry mechanism.

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubePlaylistLoader.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeMixProvider.java

- Refactors mix loading to use the PBJ endpoint.
- The PBJ endpoint exposes all information necessary for constructing an audio track, so Lavaplayer no longer needs to make a request to each video page. This speeds up loading of mixes tremendously.

Fix loading of YouTube mixes, use PBJ for faster loading.

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubePlaylistLoader.java

When loading a playlist that contains livestreams, Lavaplayer will try to fetch the `lengthSeconds` value, but being a livestream, this doesn't exist.
This PR pulls `DURATION_SEC_UNKNOWN` when `lengthSeconds` is not present.
Solution for #275.

Opt missing lengthSeconds for livestreams in playlists.

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetails.java

Check `signatureCipher` property if `cipher` is null.
Thanks to @Xavinlol for finding this.

Fix YT NullPointerException

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java

- Make request to Kraken endpoint instead, which still works.
Apparently Kraken is supposed to be deprecated/removed soon, but while it still works it makes sense to use it. I did dive into Twitch's JS to figure out if there was any way to fetch an oauth token but my efforts were for nothing.
The alternative is perhaps scraping the title from the stream page itself.
This solution was mostly taken from `youtube-dl`, so if/when Twitch decide to kill off Kraken, we could perhaps look there for a solution.
This has been tested and confirmed working:

Fix 401 on Twitch channel info req

---

common/src/main/java/com/sedmelluq/lava/common/natives/NativeLibraryLoader.java

Minor issue but fixes the `Native library {}: loading failed.` bad formatting.

Fix formatting when native load failed.

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetails.java

Current code checks if the video is a live stream by looking up for `isLiveContent` boolean, which youtube sets as `true` even if the live stream has ended, therefore it recognized ended live stream as live stream. This PR instead checks if the `duration` value is 0.
This will fix some WebM videos too, since non-live stream videos were flagged as live stream.
Example: https://www.youtube.com/watch?v=5x69RtE2hRA

Set ended live stream's isStream as false

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchProvider.java

Since 1.3.50, when search results contain [live stream](https://hastebin.com/homukicava.php) it passes `null` to `durationTextToMillis` and cause `NullPointerException`. This PR adds a simple check and removes live streams from search result.

Remove live streams from YT search result

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubePlaylistLoader.java

When playing a playlist directly from youtube, it is getting the wrong key of title, as shown below:
Trying to get `simpleText`, but it doesn't exists.
Since i didn't found any example of playlist that have a key `simpleText`, i decided to use Optional instead, to don't break scenarios that would have. If somebody knows that will never happens, so feel free to just remove that Optional and gets the `runs` key instead.
It fixes [#531](https://github.com/sedmelluq/lavaplayer/issues/531)

[YT] Fix nullable track titles from a playlist

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchProvider.java

Search results (language) are no longer depends on location #556

Fix ytsearch Result Location and Language

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/DefaultSoundCloudHtmlDataLoader.java

The string we were using to extract a json from the SoundCloud html was changed. Resolves #569

Fix SoundCloud links not loading

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/AudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/bandcamp/BandcampAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/beam/BeamAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/getyarn/GetyarnAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/http/HttpAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/local/LocalAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/nico/NicoAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/SoundCloudAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/vimeo/VimeoAudioSourceManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java

This pr changes the DefaultAudioPlayerManager class used as parameter type in loadItem to the AudioPlayerManager interface.
Reason is that now people you can create your own audioplayermanager classes

refactor: generify the loadItem method in all the SourceManagers

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/SoundCloudAudioSourceManager.java

Regex was unable to identify the track when placing a slash at the end of the URL

A repair on the regex on SoundCloudAudioSource

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetailsLoader.java

This YouTube endpoint now require `&html5=1` in request

Fix 404 response on age restricted videos

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchMusicProvider.java

When searching on YouTube Music with `"` in request it gives 400 response code because it breaks JSON syntax, PR fixing this

Fix 400 response code for searching on YouTube Music

---

main/src/main/java/com/sedmelluq/discord/lavaplayer/player/AudioPlayerManager.java
main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayerManager.java

I created this feature because I want extra data into a custom audio source manager that I wrote, this seemed like the best way to implement it while staying backward compatible with older versions.
[My current solution][nice_hack] is a hacky workaround and this would make it much easier to just cast and have the data I need from a custom AudioReference class.
[nice_hack]: https://github.com/DuncteBot/SkyBot/blob/6baf9480d939dc4c53badec4d7aff15a093ab85d/src/main/java/ml/duncte123/skybot/audio/UserContextAudioPlayerManager.java

Allow for loading a track by AudioReference
